import { StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { Scene, useMotion } from "./Scene";
import "./style.css";

const LINKEDIN = "https://www.linkedin.com/in/adarsh-viswam-95161016b/";
const DOWNLOAD_URL = (import.meta as ImportMeta & { env: { VITE_WINDOWS_DOWNLOAD_URL?: string } }).env.VITE_WINDOWS_DOWNLOAD_URL;

function Arrow({ diagonal = false }: { diagonal?: boolean }) { return <span aria-hidden="true" className="arrow">{diagonal ? "↗" : "→"}</span>; }
function Brand() { return <a className="brand" href="#top" aria-label="Autobots, back to top"><span className="brand-mark">A<span>·</span></span><span className="brand-word">AUTOBOTS<small>BY ORIGIN STUDIOS</small></span></a>; }

const frames = [
  { label: "01 / OWNER TASK", status: "Task granted", title: "Write a short note in Notepad", body: "“Open Notepad and draft a short note about tomorrow’s project review.”", intent: "Owner submits the task in Autobots." },
  { label: "02 / OBSERVE", status: "Observing", title: "See the current desktop", body: "Autobots captures the active screen and proposes one next action.", intent: "Each action is checked against the current observation." },
  { label: "03 / ACT", status: "Acting", title: "Move visibly, one step at a time", body: "The local pointer moves to the target and text is entered in the focused editor.", intent: "The local supervisor grants a one-use action." },
  { label: "04 / REVIEW", status: "Review result", title: "Check the visible result", body: "Autobots observes again and reports what it sees. The owner can stop at any moment.", intent: "An illustrated sequence; no live task is running here." },
];

function Demo() {
  const [step, setStep] = useState(0);
  const [playing, setPlaying] = useState(false);
  useEffect(() => {
    if (!playing) return;
    const timer = window.setInterval(() => setStep((value) => (value + 1) % frames.length), 2300);
    return () => window.clearInterval(timer);
  }, [playing]);
  const frame = frames[step];
  return <div className="demo-shell">
    <div className="demo-top"><span><i className="live-dot" /> PRODUCT PREVIEW</span><span>ILLUSTRATIVE WALKTHROUGH</span></div>
    <div className="demo-stage"><div className="demo-sidebar"><span className="mini-brand">A<span>·</span></span><span className="demo-side-line" /><span className="demo-side-icon">◎</span><span className="demo-side-icon">⌁</span></div><div className="demo-workspace">
      <div className="demo-windowbar"><span>Autobots <em>/</em> task view</span><span>− &nbsp; □ &nbsp; ×</span></div>
      <div className="demo-window-content" key={step}><span className="demo-step">{frame.label}</span><div className="demo-status"><span className="pulse-dot" /> {frame.status}</div><h3>{frame.title}</h3><div className="demo-document"><span className="doc-label">TASK / CURRENT VIEW</span><p>{frame.body}</p><span className="doc-caret" /></div><div className="demo-hud"><span className="hud-orb">✳</span><span>{frame.intent}</span><strong>STOP</strong></div></div>
    </div></div>
    <div className="demo-controls"><button className="demo-play" type="button" onClick={() => setPlaying(!playing)} aria-label={playing ? "Pause walkthrough" : "Play walkthrough"}>{playing ? "Ⅱ" : "▶"}</button><div className="demo-timeline" aria-label="Walkthrough steps">{frames.map((item, i) => <button key={item.label} className={i === step ? "selected" : ""} type="button" onClick={() => { setStep(i); setPlaying(false); }} aria-label={`Show ${item.label.toLowerCase()}`}><span /></button>)}</div><span className="demo-counter">0{step + 1} / 0{frames.length}</span></div>
  </div>;
}

function App() {
  const motion = useMotion();
  const [menuOpen, setMenuOpen] = useState(false);
  return <>
    <Scene motion={motion} /><div className="noise" aria-hidden="true" /><div className="progress-track" aria-hidden="true"><div /></div>
    <header className="site-header"><Brand /><nav className={menuOpen ? "main-nav open" : "main-nav"} aria-label="Main navigation"><a href="#experience" onClick={() => setMenuOpen(false)}>Experience</a><a href="#demo" onClick={() => setMenuOpen(false)}>Demo</a><a href="#how" onClick={() => setMenuOpen(false)}>How it works</a><a href="/developer/index.html">Developer</a></nav><a className="header-cta" href="#download">GET THE APP <Arrow diagonal /></a><button className="menu-toggle" type="button" aria-label={menuOpen ? "Close menu" : "Open menu"} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? "×" : "☰"}</button></header>
    <main id="top">
      <section className="panel hero" aria-labelledby="hero-title"><div className="hero-meta"><span><i className="live-dot" /> A NEW WAY TO WORK WITH YOUR DESKTOP</span><span>01 / 06</span></div><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line" /> YOUR DESKTOP, IN MOTION</div><h1 id="hero-title">Think it.<br /><em>Watch it</em><br />happen<span className="period">.</span></h1><p>Autobots is a visible desktop assistant for Windows. Give it a task, watch each step unfold, and stay in control with a local STOP button.</p><div className="button-row"><a className="button button-lime" href="#demo">SEE IT IN ACTION <Arrow diagonal /></a><a className="text-link" href="#how">EXPLORE HOW IT WORKS <Arrow /></a></div></div><div className="hero-side-note"><span className="side-line" />AUTONOMY,<br />WITH YOU IN CONTROL</div><a className="scroll-cue" href="#experience"><span className="scroll-icon">↓</span><span>SCROLL TO EXPLORE</span></a><div className="scene-caption"><span>01 — THE AUTOBOTS CORE</span><span>MOVE YOUR CURSOR</span></div></section>
      <section className="panel experience" id="experience" aria-labelledby="experience-title"><div className="section-kicker"><span>01 / THE EXPERIENCE</span><span>ONE TASK. VISIBLE STEPS.</span></div><div className="section-copy right-copy"><p className="overline">THE IDEA</p><h2 id="experience-title">Your intention.<br /><em>Real motion.</em></h2><p className="section-description">Autobots observes your screen, proposes a step, and moves the real pointer in your signed-in Windows session. It checks the view again before continuing.</p><div className="feature-rule"><span>01</span><strong>Describe a bounded task</strong><Arrow /></div><div className="feature-rule"><span>02</span><strong>Follow every visible action</strong><Arrow /></div><div className="feature-rule"><span>03</span><strong>Stop locally at any time</strong><Arrow /></div></div><div className="section-index">THE ASSISTANT THAT SHOWS ITS WORK <span>↗</span></div></section>
      <section className="panel demo-panel" id="demo" aria-labelledby="demo-title"><div className="section-kicker"><span>02 / THE DEMO</span><span>AN ILLUSTRATED PRODUCT FLOW</span></div><div className="demo-layout"><div className="demo-intro"><p className="overline">SEE THE LOOP</p><h2 id="demo-title">From prompt<br />to <em>progress.</em></h2><p className="section-description">A short walkthrough of a Notepad task. Choose a step or press play to see how Autobots moves from an owner instruction to a visible result.</p><span className="fine-print">Illustrative interface sequence. This is not a recording or a live automation session.</span></div><Demo /></div></section>
      <section className="panel control" id="control" aria-labelledby="control-title"><div className="section-kicker"><span>03 / YOUR CONTROL</span><span>LOCAL FIRST</span></div><div className="section-copy right-copy"><p className="overline">BUILT AROUND THE OWNER</p><h2 id="control-title">The power<br />to <em>pause everything.</em></h2><p className="section-description">Only a task you submit can start desktop input. The local supervisor checks each proposed action against the task and current screen. STOP revokes the task lease even when the network is unavailable.</p><div className="control-tags"><span>OWNER-GRANTED TASKS</span><span>ONE INPUT LEASE</span><span>OFFLINE STOP</span></div><p className="fine-print">STOP prevents future input; it cannot undo actions already completed in another app.</p></div><div className="stop-graphic" aria-hidden="true"><span className="stop-cross">×</span><span>STOP</span><small>CTRL + ALT + SHIFT + S</small></div></section>
      <section className="panel how" id="how" aria-labelledby="how-title"><div className="section-kicker"><span>04 / HOW IT WORKS</span><span>THREE SIMPLE BEATS</span></div><div className="how-intro"><p className="overline">A CLEAR LOOP</p><h2 id="how-title">You lead.<br /><em>Autobots moves.</em></h2></div><div className="steps"><article><span className="step-number">01 /</span><div className="step-symbol">⌁</div><h3>Give it a goal</h3><p>Type a task in the Windows app. Your instruction defines what Autobots may do and for how long.</p></article><article><span className="step-number">02 /</span><div className="step-symbol">◎</div><h3>Watch it work</h3><p>It observes the primary display, moves the pointer visibly, and checks the result after each action.</p></article><article><span className="step-number">03 /</span><div className="step-symbol">⊘</div><h3>Stay in charge</h3><p>Use the pilot bar, tray menu, or global shortcut to stop. Autobots reports when it needs your input.</p></article></div><p className="setup-note"><strong>FIRST RUN /</strong> With pilot access, extract the Windows ZIP, run Autobots.Desktop.exe, connect your owner account, then submit a task. You can stop from the pilot bar or with Ctrl + Alt + Shift + S.</p></section>
      <section className="panel platforms" id="download" aria-labelledby="platforms-title"><div className="section-kicker"><span>05 / GET AUTOBOTS</span><span>THE PLATFORM ROADMAP</span></div><div className="platform-copy"><p className="overline">START ON WINDOWS</p><h2 id="platforms-title">Made for<br /><em>your desktop.</em></h2><p className="section-description">The current owner pilot runs on Windows 11. Native macOS and Linux versions are planned.</p></div><div className="platform-cards"><article className="platform-card windows-card"><div className="platform-head"><span className="platform-glyph">⊞</span><span className="platform-status"><i className="live-dot" /> PRIVATE PILOT</span></div><h3>Windows</h3><p>Windows 11 · x64 · owner access</p>{DOWNLOAD_URL ? <a className="platform-button" href={DOWNLOAD_URL} download>DOWNLOAD WINDOWS APP <Arrow diagonal /></a> : <a className="platform-button" href={LINKEDIN} target="_blank" rel="noreferrer">REQUEST PILOT ACCESS <Arrow diagonal /></a>}<small>{DOWNLOAD_URL ? "Pilot bundle. Follow the included install instructions." : "Public download opens when the release is ready."}</small></article><article className="platform-card future-card"><div className="platform-head"><span className="platform-glyph apple">●</span><span className="platform-status muted">COMING SOON</span></div><h3>macOS</h3><p>Native experience in the future roadmap.</p><span className="future-line">IN DEVELOPMENT <Arrow /></span></article><article className="platform-card future-card"><div className="platform-head"><span className="platform-glyph">⌘</span><span className="platform-status muted">COMING SOON</span></div><h3>Linux</h3><p>Built on the same shared app foundation.</p><span className="future-line">IN DEVELOPMENT <Arrow /></span></article></div></section>
      <section className="panel maker" id="developer" aria-labelledby="maker-title"><div className="section-kicker"><span>06 / THE HUMAN BEHIND IT</span><span>MEET THE DEVELOPER</span></div><div className="maker-copy"><p className="overline">CREATED BY ADARSH VISWAM</p><h2 id="maker-title">A person<br />behind the <em>possibility.</em></h2><p className="section-description">Learn about the developer building Autobots, his work, and the ideas behind the project.</p><a className="button button-lime" href="/developer/index.html">MEET ADARSH <Arrow diagonal /></a></div><div className="maker-monogram" aria-hidden="true">AV<span>↗</span></div></section>
    </main>
    <footer className="site-footer"><Brand /><p>DESKTOP INTELLIGENCE, WITH THE OWNER IN CONTROL.</p><div><a href="/developer/index.html">DEVELOPER</a><a href={LINKEDIN} target="_blank" rel="noreferrer">LINKEDIN ↗</a><a href="#top">BACK TO TOP ↑</a></div><small>© {new Date().getFullYear()} ORIGIN STUDIOS</small></footer>
  </>;
}

createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
